version: "3"

services: 
  redis-server:
    image: redis
    # command: 'redis-server'
    # command: >
    #  sh -c 'redis-cli -h redis '
  node-app:
    restart: always
    build: .
    ports:
      - "8080:8081"